### ISSUE TITLE
using globals in perks breaks entangled

### ISSUE THREAD

**Issue by bgkillas** [Conga0/Apotheosis#43]
can you use the argument for how many of the same perk entities the player has to not break entangled? for oversized shield and void perk, this is how entangled does shield
![image](https://github.com/user-attachments/assets/d1420239-39a4-488e-b9a9-23c24dc46fac)

**Comment by Conga0** [comment]
I don't fully understand, are you saying to check for the entity count of the perks rather than scan for a global variable to get the current perk count?

This could work for oversized shield as it's effects are localised but Void's effects should be global between all the voids taken by all players, is there an example of how to scan for the perk count across all players?

**Comment by bgkillas** [comment]
yeah since if its in a global, that global will iterate if anyone gets it, making unusual shield sizes, aspecially since the global will be run multiple times if we need to re-make the client entity
https://github.com/IntQuant/noita_entangled_worlds/blob/master/quant.ew/files/core/perk_fns.lua#L171 is an example of how we track perks for players, so perks are stored in the "ew_current_perks" tagged variable storage component on each client, and all client entities can be found under the "ew_peer" tag

**Comment by bgkillas** [comment]
#45
